import {
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  Type,
  Square,
  Box,
  MousePointerClick,
  Link as LinkIcon,
  Image,
  List,
  ListOrdered,
  Table,
  FormInput,
  TextCursorInput,
  AlignLeft,
  Code,
  Quote,
  Minus,
  Bold,
  Italic,
  Highlighter,
  Video,
  Music,
  Frame,
  ImageOff,
  ChevronDownSquare,
  type LucideIcon,
} from "lucide-react";
import type { HtmlTag } from "../types";

export type TagMeta = {
  tag: HtmlTag;
  label: string; // nama ramah anak (Bahasa Indonesia)
  hint: string;
  icon: LucideIcon;
  /** Bisa diisi block lain di dalamnya */
  container: boolean;
  /** Menampung teks yang bisa diketik anak */
  text: boolean;
  /** Tag self-closing (tidak punya children/teks) */
  void?: boolean;
  /** Atribut yang bisa diedit */
  attrs?: Array<"src" | "alt" | "href">;
  /** Warna aksen block di canvas */
  color: string;
  /** Kelompok di sidebar (diisi otomatis) */
  category?: TagCategory;
};

export type TagCategory =
  | "Teks"
  | "Layout"
  | "Daftar & Tabel"
  | "Form & Input"
  | "Media"
  | "Lainnya";

export const TAG_CATALOG: TagMeta[] = [
  {
    tag: "h1",
    label: "Judul 1",
    hint: "Heading paling besar",
    icon: Heading1,
    container: false,
    text: true,
    color: "#ef4444",
  },
  {
    tag: "h2",
    label: "Judul 2",
    hint: "Heading sedang",
    icon: Heading2,
    container: false,
    text: true,
    color: "#f97316",
  },
  {
    tag: "h3",
    label: "Judul 3",
    hint: "Heading kecil",
    icon: Heading3,
    container: false,
    text: true,
    color: "#f59e0b",
  },
  {
    tag: "h4",
    label: "Judul 4",
    hint: "Heading lebih kecil",
    icon: Heading4,
    container: false,
    text: true,
    color: "#eab308",
  },
  {
    tag: "h5",
    label: "Judul 5",
    hint: "Heading kecil",
    icon: Heading5,
    container: false,
    text: true,
    color: "#84cc16",
  },
  {
    tag: "h6",
    label: "Judul 6",
    hint: "Heading terkecil",
    icon: Heading6,
    container: false,
    text: true,
    color: "#22c55e",
  },
  {
    tag: "p",
    label: "Paragraf",
    hint: "Teks panjang",
    icon: Type,
    container: false,
    text: true,
    color: "#3b82f6",
  },
  {
    tag: "span",
    label: "Potongan Teks",
    hint: "Teks pendek di dalam baris",
    icon: Type,
    container: false,
    text: true,
    color: "#0ea5e9",
  },
  {
    tag: "div",
    label: "Kotak",
    hint: "Wadah untuk menumpuk block",
    icon: Square,
    container: true,
    text: false,
    color: "#6366f1",
  },
  {
    tag: "section",
    label: "Bagian",
    hint: "Kelompok besar konten",
    icon: Box,
    container: true,
    text: false,
    color: "#8b5cf6",
  },
  {
    tag: "article",
    label: "Artikel",
    hint: "Konten mandiri",
    icon: Box,
    container: true,
    text: false,
    color: "#7c3aed",
  },
  {
    tag: "header",
    label: "Kepala",
    hint: "Bagian atas halaman",
    icon: Box,
    container: true,
    text: false,
    color: "#a855f7",
  },
  {
    tag: "footer",
    label: "Kaki",
    hint: "Bagian bawah halaman",
    icon: Box,
    container: true,
    text: false,
    color: "#9333ea",
  },
  {
    tag: "nav",
    label: "Navigasi",
    hint: "Menu navigasi",
    icon: Box,
    container: true,
    text: false,
    color: "#c026d3",
  },
  {
    tag: "main",
    label: "Konten Utama",
    hint: "Isi utama halaman",
    icon: Box,
    container: true,
    text: false,
    color: "#d946ef",
  },
  {
    tag: "aside",
    label: "Samping",
    hint: "Konten sampingan",
    icon: Box,
    container: true,
    text: false,
    color: "#db2777",
  },
  {
    tag: "button",
    label: "Tombol",
    hint: "Bisa diklik",
    icon: MousePointerClick,
    container: false,
    text: true,
    color: "#22c55e",
  },
  {
    tag: "a",
    label: "Tautan",
    hint: "Link ke halaman lain",
    icon: LinkIcon,
    container: false,
    text: true,
    attrs: ["href"],
    color: "#14b8a6",
  },
  {
    tag: "img",
    label: "Gambar",
    hint: "Foto / gambar",
    icon: Image,
    container: false,
    text: false,
    void: true,
    attrs: ["src", "alt"],
    color: "#a855f7",
  },
  {
    tag: "ul",
    label: "Daftar Tak Berurut",
    hint: "Berisi item daftar",
    icon: List,
    container: true,
    text: false,
    color: "#ec4899",
  },
  {
    tag: "ol",
    label: "Daftar Berurut",
    hint: "Daftar bernomor",
    icon: ListOrdered,
    container: true,
    text: false,
    color: "#f43f5e",
  },
  {
    tag: "li",
    label: "Item Daftar",
    hint: "Satu baris dalam daftar",
    icon: ListOrdered,
    container: false,
    text: true,
    color: "#fb7185",
  },
  {
    tag: "table",
    label: "Tabel",
    hint: "Wadah tabel",
    icon: Table,
    container: true,
    text: false,
    color: "#0d9488",
  },
  {
    tag: "thead",
    label: "Kepala Tabel",
    hint: "Baris judul tabel",
    icon: Table,
    container: true,
    text: false,
    color: "#14b8a6",
  },
  {
    tag: "tbody",
    label: "Isi Tabel",
    hint: "Baris isi tabel",
    icon: Table,
    container: true,
    text: false,
    color: "#2dd4bf",
  },
  {
    tag: "tr",
    label: "Baris Tabel",
    hint: "Satu baris tabel",
    icon: Table,
    container: true,
    text: false,
    color: "#5eead4",
  },
  {
    tag: "th",
    label: "Sel Judul",
    hint: "Sel header tabel",
    icon: Table,
    container: false,
    text: true,
    color: "#99f6e4",
  },
  {
    tag: "td",
    label: "Sel",
    hint: "Satu sel tabel",
    icon: Table,
    container: false,
    text: true,
    color: "#ccfbf1",
  },
  {
    tag: "form",
    label: "Formulir",
    hint: "Wadah input",
    icon: FormInput,
    container: true,
    text: false,
    color: "#0891b2",
  },
  {
    tag: "input",
    label: "Input",
    hint: "Kolom isian",
    icon: TextCursorInput,
    container: false,
    text: false,
    void: true,
    color: "#06b6d4",
  },
  {
    tag: "textarea",
    label: "Kotak Teks",
    hint: "Input teks panjang",
    icon: AlignLeft,
    container: false,
    text: true,
    color: "#38bdf8",
  },
  {
    tag: "select",
    label: "Pilihan",
    hint: "Dropdown pilihan",
    icon: ChevronDownSquare,
    container: true,
    text: false,
    color: "#0ea5e9",
  },
  {
    tag: "option",
    label: "Opsi",
    hint: "Satu pilihan",
    icon: ChevronDownSquare,
    container: false,
    text: true,
    color: "#7dd3fc",
  },
  {
    tag: "label",
    label: "Label",
    hint: "Teks label input",
    icon: AlignLeft,
    container: false,
    text: true,
    color: "#93c5fd",
  },
  {
    tag: "blockquote",
    label: "Kutipan",
    hint: "Kutipan panjang",
    icon: Quote,
    container: true,
    text: false,
    color: "#64748b",
  },
  {
    tag: "pre",
    label: "Teks Pratayang",
    hint: "Teks monospace",
    icon: Code,
    container: false,
    text: true,
    color: "#475569",
  },
  {
    tag: "code",
    label: "Kode",
    hint: "Potongan kode",
    icon: Code,
    container: false,
    text: true,
    color: "#334155",
  },
  {
    tag: "hr",
    label: "Garis Pembatas",
    hint: "Pemisah horizontal",
    icon: Minus,
    container: false,
    text: false,
    void: true,
    color: "#94a3b8",
  },
  {
    tag: "br",
    label: "Ganti Baris",
    hint: "Pindah baris",
    icon: Minus,
    container: false,
    text: false,
    void: true,
    color: "#cbd5e1",
  },
  {
    tag: "strong",
    label: "Tebal",
    hint: "Teks tebal",
    icon: Bold,
    container: false,
    text: true,
    color: "#e11d48",
  },
  {
    tag: "em",
    label: "Miring",
    hint: "Teks miring",
    icon: Italic,
    container: false,
    text: true,
    color: "#be123c",
  },
  {
    tag: "small",
    label: "Kecil",
    hint: "Teks kecil",
    icon: Type,
    container: false,
    text: true,
    color: "#f43f5e",
  },
  {
    tag: "mark",
    label: "Tandai",
    hint: "Teks disorot",
    icon: Highlighter,
    container: false,
    text: true,
    color: "#facc15",
  },
  {
    tag: "sub",
    label: "Subskrip",
    hint: "Teks di bawah",
    icon: Type,
    container: false,
    text: true,
    color: "#a3e635",
  },
  {
    tag: "sup",
    label: "Superskrip",
    hint: "Teks di atas",
    icon: Type,
    container: false,
    text: true,
    color: "#65a30d",
  },
  {
    tag: "video",
    label: "Video",
    hint: "Pemutar video",
    icon: Video,
    container: false,
    text: false,
    void: true,
    attrs: ["src"],
    color: "#4f46e5",
  },
  {
    tag: "audio",
    label: "Audio",
    hint: "Pemutar audio",
    icon: Music,
    container: false,
    text: false,
    void: true,
    attrs: ["src"],
    color: "#4338ca",
  },
  {
    tag: "iframe",
    label: "Iframe",
    hint: "Sisipan halaman",
    icon: Frame,
    container: false,
    text: false,
    attrs: ["src"],
    color: "#3730a3",
  },
  {
    tag: "figure",
    label: "Figure",
    hint: "Wadah gambar/media",
    icon: ImageOff,
    container: true,
    text: false,
    color: "#1e40af",
  },
  {
    tag: "figcaption",
    label: "Keterangan Gambar",
    hint: "Caption figure",
    icon: ImageOff,
    container: false,
    text: true,
    color: "#1d4ed8",
  },
  {
    tag: "details",
    label: "Detail",
    hint: "Konten yang bisa dibuka",
    icon: ChevronDownSquare,
    container: true,
    text: false,
    color: "#0f766e",
  },
  {
    tag: "summary",
    label: "Ringkasan",
    hint: "Judul detail",
    icon: ChevronDownSquare,
    container: false,
    text: true,
    color: "#115e59",
  },
  {
    tag: "dl",
    label: "Daftar Definisi",
    hint: "Daftar istilah",
    icon: List,
    container: true,
    text: false,
    color: "#164e63",
  },
  {
    tag: "dt",
    label: "Istilah",
    hint: "Istilah definisi",
    icon: Type,
    container: false,
    text: true,
    color: "#155e75",
  },
  {
    tag: "dd",
    label: "Definisi",
    hint: "Penjelasan istilah",
    icon: AlignLeft,
    container: false,
    text: true,
    color: "#0e7490",
  },
];

export const TAG_META: Record<HtmlTag, TagMeta> = TAG_CATALOG.reduce(
  (acc, meta) => {
    acc[meta.tag] = meta;
    return acc;
  },
  {} as Record<HtmlTag, TagMeta>,
);

export function isContainer(tag: HtmlTag): boolean {
  return TAG_META[tag].container;
}

/** Urutan kategori di sidebar. */
export const CATEGORY_ORDER: TagCategory[] = [
  "Teks",
  "Layout",
  "Daftar & Tabel",
  "Form & Input",
  "Media",
  "Lainnya",
];

const CATEGORY_MAP: Record<HtmlTag, TagCategory> = {
  h1: "Teks", h2: "Teks", h3: "Teks", h4: "Teks", h5: "Teks", h6: "Teks",
  p: "Teks", span: "Teks", strong: "Teks", em: "Teks", small: "Teks",
  mark: "Teks", sub: "Teks", sup: "Teks", blockquote: "Teks",
  pre: "Teks", code: "Teks",
  div: "Layout", section: "Layout", article: "Layout", header: "Layout",
  footer: "Layout", nav: "Layout", main: "Layout", aside: "Layout",
  figure: "Layout", figcaption: "Layout", details: "Layout", summary: "Layout",
  ul: "Daftar & Tabel", ol: "Daftar & Tabel", li: "Daftar & Tabel",
  table: "Daftar & Tabel", thead: "Daftar & Tabel", tbody: "Daftar & Tabel",
  tr: "Daftar & Tabel", th: "Daftar & Tabel", td: "Daftar & Tabel",
  dl: "Daftar & Tabel", dt: "Daftar & Tabel", dd: "Daftar & Tabel",
  form: "Form & Input", input: "Form & Input", textarea: "Form & Input",
  select: "Form & Input", option: "Form & Input", label: "Form & Input",
  button: "Form & Input",
  img: "Media", video: "Media", audio: "Media", iframe: "Media",
  a: "Lainnya", hr: "Lainnya", br: "Lainnya",
};

/** Catalog lengkap dengan kategori terisi. */
export const TAG_CATALOG_CATEGORIZED: TagMeta[] = TAG_CATALOG.map((m) => ({
  ...m,
  category: CATEGORY_MAP[m.tag] ?? "Lainnya",
}));
